TST Check

diff --git a/azure/posix-sdist.yml b/azure/posix-sdist.yml
--- a/azure/posix-sdist.yml
+++ b/azure/posix-sdist.yml
@@ -105,11 +105,11 @@ jobs:
             TOKEN="$SCIKIT_LEARN_STAGING_UPLOAD_TOKEN"
           fi
 
-          echo $SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN
-          echo $TOKEN
-          if [ "$?" != "0" ]; then
-            echo "##[warning] Could not find anaconda.org upload token in secret variables"
-          fi
+          $SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN
+          echo $?
+          # if [ "$TOKEN" == ]; then
+          #   echo "##[warning] Could not find anaconda.org upload token in secret variables"
+          # fi
 
           echo "##vso[task.setvariable variable=TOKEN]$TOKEN"
           echo "##vso[task.setvariable variable=ANACONDA_ORG]$ANACONDA_ORG"
